language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install -B test jacoco:report coveralls:report

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
